
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, UnderlineType, TabStopType, TabStopPosition } from 'docx';
import { saveAs } from 'file-saver';
import type { ParsedCvData } from '@/types/cv';

const createSection = (title: string, content: string | undefined | null, headingLevel: HeadingLevel): Paragraph[] => {
  const paragraphs: Paragraph[] = [];
  if (title) {
    paragraphs.push(
      new Paragraph({
        text: title,
        heading: headingLevel,
        spacing: { before: 200, after: 100 },
      })
    );
  }
  if (content) {
    content.split('\n').forEach(line => {
      if (line.trim()) { // Avoid empty paragraphs
        // Basic bullet point handling
        if (line.trim().startsWith('- ') || line.trim().startsWith('* ')) {
          paragraphs.push(
            new Paragraph({
              children: [
                new TextRun({ text: line.substring(line.indexOf(' ') + 1).trim() }),
              ],
              bullet: { level: 0 },
              indent: { left: 720 }, // 0.5 inch indent
              style: 'normalPara',
            })
          );
        } else {
          paragraphs.push(
            new Paragraph({
              children: [new TextRun(line.trim())],
              style: 'normalPara',
            })
          );
        }
      }
    });
  }
  return paragraphs;
};


export async function generateDocxForModernTemplate(data: ParsedCvData): Promise<void> {
  const { name, contactInformation, objective, experience, technicalSkills, personalSkills, education, certifications, interest } = data;

  const email = contactInformation.match(/[\w.-]+@[\w.-]+\.\w+/)?.[0];
  const phone = contactInformation.match(/(\(\d{3}\)\s*\d{3}-\d{4}|\d{3}-\d{3}-\d{4}|\d{10})/)?.[0];
  const linkedIn = contactInformation.match(/linkedin\.com\/in\/[\w-]+/)?.[0];

  const contactParts: string[] = [];
  if (email) contactParts.push(email);
  if (phone) contactParts.push(phone);
  if (linkedIn) contactParts.push(linkedIn);


  const doc = new Document({
    creator: "CV-Genius",
    title: `${name || 'CV'} - Modern Template`,
    description: "Curriculum Vitae generated by CV-Genius",
    styles: {
      default: {
        heading1: {
          run: { size: 48, bold: true, font: "Calibri" }, // 24pt
          paragraph: { alignment: AlignmentType.CENTER, spacing: { after: 200 } },
        },
        heading2: {
          run: { size: 32, bold: true, font: "Calibri" }, // 16pt
          paragraph: { spacing: { before: 300, after: 150 } },
        },
        heading3: {
            run: { size: 28, bold: true, font: "Calibri", color: "4F81BD" }, // 14pt, Accent color like
            paragraph: { spacing: { before: 240, after: 120 } },
        },
      },
      paragraphStyles: [
        {
          id: "normalPara",
          name: "Normal Para",
          basedOn: "Normal",
          next: "Normal",
          quickFormat: true,
          run: { font: "Calibri", size: 22 }, // 11pt
          paragraph: { spacing: { after: 100 } },
        },
        {
          id: "contactInfo",
          name: "Contact Info",
          basedOn: "Normal",
          next: "Normal",
          quickFormat: true,
          run: { font: "Calibri", size: 20 }, // 10pt
          paragraph: { alignment: AlignmentType.CENTER, spacing: { after: 200 } },
        }
      ],
    },
    sections: [{
      properties: {
        page: {
          margin: {
            top: 720, // 0.5 inch
            right: 720,
            bottom: 720,
            left: 720,
          },
        },
      },
      children: [
        new Paragraph({
          text: name || "Your Name",
          heading: HeadingLevel.HEADING_1,
          alignment: AlignmentType.CENTER,
        }),
        new Paragraph({
          text: contactParts.join(' | '),
          style: 'contactInfo',
          alignment: AlignmentType.CENTER,
        }),
        ...(objective ? createSection("Objective", objective, HeadingLevel.HEADING_3) : []),
        ...(experience ? createSection("Experience", experience, HeadingLevel.HEADING_3) : []),
        ...(education ? createSection("Education", education, HeadingLevel.HEADING_3) : []),
        ...(technicalSkills ? createSection("Technical Skills", technicalSkills, HeadingLevel.HEADING_3) : []),
        ...(personalSkills ? createSection("Personal Skills", personalSkills, HeadingLevel.HEADING_3) : []),
        ...(certifications ? createSection("Certifications", certifications, HeadingLevel.HEADING_3) : []),
        ...(interest ? createSection("Interests", interest, HeadingLevel.HEADING_3) : []),
      ],
    }],
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, `${(name || 'CV').replace(/\s+/g, '_')}_Modern.docx`);
}
